"""host compromised flag

Revision ID: 8d9204d10613
Revises: 1ed024d8871b
Create Date: 2025-03-08 13:23:23.310757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9204d10613'
down_revision = '1ed024d8871b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_compromised', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_compromised', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('admin_compromised')
        batch_op.drop_column('user_compromised')

    # ### end Alembic commands ###
