"""Added sysinfos columns for host

Revision ID: 9bee403e5501
Revises: 8d9204d10613
Create Date: 2025-03-09 09:56:07.675167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bee403e5501'
down_revision = '8d9204d10613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_users', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_profiles', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nics', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('nics')
        batch_op.drop_column('user_profiles')
        batch_op.drop_column('local_users')

    # ### end Alembic commands ###
